name: Push Data to MongoDB

on:
  push:
    branches:
      - main  # Replace with the branch you want to trigger this on

jobs:
  push_data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name : install mongo
      run: |
        wget https://fastdl.mongodb.org/tools/db/mongodb-database-tools-debian10-x86_64-100.8.0.deb
        sudo dpkg -i mongodb-database-tools-debian10-x86_64-100.8.0.deb
    - name: Push Data to MongoDB
      run: |
        chmod +x push_data.sh  # Make the Bash script executable
        ./push_data.sh  # Execute the Bash script
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
